### ISSUE TITLE
LS: Review "Definition of Done" in Wiki & shift to md file

### ISSUE THREAD

**Issue by dsturgell** [RetailDevCrews/helium#1]
Please review all criteria in Wiki and review the below for recommendations.

- **Code changes reviewed** -  Agreement on # of reviewers?
- **Testing is automated**  -- - recommend add "add additional testing for new capability (A/N)"
- **Build and deployment of change is automated** -- Currently in Bluebell vs public repo, how do we want to define?

**Comment by bartr** [comment]
Closed with PR #66
