### ISSUE TITLE
Create "Task" template

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#117]

**Comment by dsturgell** [comment]
Proposing the following format:

##Description:

##Done Checklist:

## Definition of Done
- [ ] Code changes reviewed & signed off
- [ ]Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Code changes checked into master
- [ ] All existing automated tests (unit and/or e2e) pass successfully, new tests added as needed
- [ ] CI completes successfully
- [ ] CD completes successfully
- [ ] New changes in smoke test for 48hrs

**Comment by bartr** [comment]
We need to push the templates to the language and IMDb repos. Most are just in Helium.

**Comment by dsturgell** [comment]
Yep…I was hoping there was an easy way to do that.

I also want to get into Repo Template – so I can clone for Health & Wellness.  We are thinking of calling it “project Oxygen” (as Anne said, oxygen feeds “fire”)

**Comment by bartr** [comment]
We should look into if you create a repo from a template and update the template, can you git pull the template updates?  Wouldn't work for the current repos, but could be a way to share. I'm not aware of a way with our existing repos other than cloning, copying and pushing via PR.
