### ISSUE TITLE
Implement 12 Factor disposability into codebases

### ISSUE THREAD

**Issue by evillgenius75** [retaildevcrews/helium#166]
- [x] helium-csharp
- [x] helium-java
- [x] helium-typescript
- [x] webv

## Description

- When developing software that can b e run in complex orchestration systems it is important that disposability is taken into consideration when designing a service. The code bases for Helium should include handlers for sigterm and connection requests to be handled when Kubernetes decides to reassess the load across the cluster.

## Acceptance Criteria

- [ ] Application should gracefully capture SIGTERM from the process handler
- [ ] For a web process, graceful shutdown is achieved by ceasing to listen on the service port (thereby refusing any new requests), allowing any current requests to finish, and then exiting.
- [ ] For a worker process, graceful shutdown is achieved by returning the current job to the work queue. To facilitate this all jobs are reentrant, which typically is achieved by wrapping the results in a transaction, or making the operation idempotent.

## Constraints

- Minimal use of Pre-Stop triggers to be used if possible. The code should be able to handle all needed processes based on the `TERM` signal from the process handler.

## Resources

- [Termination of Kubernetes Pods ](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods)
-  [Kubernetes Mockup of a graceful termination using preStop Hook](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#define-poststart-and-prestop-handlers)

Reference: [Definition of Done](../../docs/EngineeringPractices.md)

**Comment by bartr** [comment]
Based on the research I've done, helium-csharp should handle this correctly via the ctl-c handler as it should handle the signals. You should get log messages that there was a graceful shutdown. File an issue if you don't.
