### ISSUE TITLE
Migrate WebValidate Source to own repo

### ISSUE THREAD

**Issue by evillgenius75** [retaildevcrews/helium#181]
## Description:
- Currently smoker codebase resides in retaildevcrews/helium repository along with demo documentation and engineering processes.
- [ ] Create a new repository under retaildevcrews called smoker
- [ ] Migrate source code and CI from retaildevcrews/helium
- [ ] Verify smoker is deployed to all environments

**Comment by bartr** [comment]
Initial migration is complete. PR to remove code from Helium submitted
