### ISSUE TITLE
Java: Make code compatible with compiling and running from VS Code with Java tooling installed

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/helium#204]
## Problem Statement
- Currently, the code base is compiled using IntelliJ.  However, that isn't an easy requirement for onboarding new devs or working with HoL/OH type events.

## Proposed Solution
- Update the code to comply with requirements of VSCode + Extensions to ensure it can build, run, and debug via VS Code.  Changes are mostly clean-up type things with few minor code changes as can be found via diff of this branch: https://github.com/retaildevcrews/helium-java/tree/vsCodeTesting.

**Comment by bartr** [comment]
Closed as part of migration to web flux
