### ISSUE TITLE
Deploy Gelato

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#22]
- Deploy gelato to bluebell subscription
- setup app insights
- setup alerts
- setup smoke test
- setup CI-CD
- run as a "production" app
- fork repo after PR is approved

**Comment by evillgenius75** [comment]
Currently blocked by error in springboot keyvault module. Error log attached.
[2020_01_09_RD0004FFD0F304_default_docker.log](https://github.com/retaildevcrews/helium/files/4041334/2020_01_09_RD0004FFD0F304_default_docker.log)
@jyotsnaravikumar @bartr

**Comment by evillgenius75** [comment]
Closed by [helium-java PR#14](https://github.com/retaildevcrews/helium-java/pull/14)
