### ISSUE TITLE
Refactor QueryActorWorkerAsync(string) and QueryMovieWorkerAsync(string)

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/helium#241]
## Description:
- These two functions appear identical other than return type.  The code could be refactored to a generic and moved dalMain.cs and scoping changed to private.  The resulting code might be something like:

        private async Task<IEnumerable<T>> InternalCosmosDBSqlQuery<T>(string sql)
        {
            // run query
            var query = _cosmosDetails.Container.GetItemQueryIterator<T>(sql, requestOptions: _cosmosDetails.QueryRequestOptions);

            List<T> results = new List<T>();

            while (query.HasMoreResults)
            {
                foreach (var doc in await query.ReadNextAsync().ConfigureAwait(false))
                {
                    results.Add(doc);
                }
            }
            return results;
        }

- Additionally, we could put a type constraint on the generic declaration if we create a base data type that contains something like Id and PartitionKey from which the data classes inherit.  Then the method declaration could look like:
         private async Task<IEnumerable<T>> InternalCosmosDBSqlQuery<T>(string sql)
            where T : DataObjectBase     {...}
 
- The other DAL classes need to be reviewed for the same and similar code that may be made generic.

**Comment by bartr** [comment]
We should be able to use one generic function for all of the queries. Genre is a List<string>, so would not be able to use where T: ...

I don't think we are, but need to verify we're not double copying the results from a stream -> memory -> stream. Should go stream -> stream.

**Comment by jofultz** [comment]
This issue was closed by PR 59: https://github.com/retaildevcrews/helium-csharp/pull/59.
