### ISSUE TITLE
Standardize environment variables:

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#329]
Environment Variables:
KEYVAULT_NAME
AUTH_TYPE

Command Line Arguments:
--keyvault-name (-k)
--auth-type (-a)
--dry-run (-d)
--help (-h)

Repo Updated:
- [x] typescript
- [ ] java
- [x] csharp
- [x] webv

References #326

**Comment by aflinchb** [comment]
I believe Jeremy's recent PR completed this for typescript, just need to implement dry run
https://github.com/retaildevcrews/helium-typescript/pull/130
