### ISSUE TITLE
Sample IMDb data command line input returns an error

### ISSUE THREAD

**Issue by tobiaswright** [retaildevcrews/helium#332]
## Description
While following the instructions to use IMDb sample database, on  the instruction to create the container:
```
az cosmosdb sql container create -p /partitionKey --idx @index.json -g $Imdb_RG -a $Imdb_Name -d $Imdb_DB -n $Imdb_Col
```
I receive an error:

```
Expecting value: line 1column 1 (char 0)
```

When ```--idx @index.json``` was removed was able to continue

## Expected Behavior
Expect the readme to accept all CLI commands

## Reproduce
1. Go to [IMBd README](https://github.com/retaildevcrews/imdb)
2. Follow readme instruction
3. Input container creation
4. Returns ```Expecting value: line 1column 1 (char 0)```

## Additional Context 
![Screenshot from 2020-03-30 01-45-46](https://user-images.githubusercontent.com/759066/77896246-fbbd0480-7245-11ea-8035-4a5f45d2fb8c.png)

**Comment by dsturgell** [comment]
Recommendation: Take out the --idx parameter
