### ISSUE TITLE
Update CosmosDB Consistency Level to Session for All Languages

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/helium#390]
## Description:
We need to ensure that the consistency level for CosmosDB connection is set to ConsistencyLevel.SESSION for all codebases.

### Completed 
- [x] .Net
- [ ] Node
- [x] Java

**Comment by bartr** [comment]
@jofultz - I believe this is already done for Java - if so, LMK

@tobiaswright  - can you update TS?

**Comment by jofultz** [comment]
@bartr - PR submitted....I'll pre-emptively check the box :)
