### ISSUE TITLE
Developer Experience / Codespaces

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#396]
- [x] helium-csharp
- [ ] helium-java
- [x] helium-typescrript
- [x] webv
- [x] imdb

- target "local" dev (this includes VMs)
- target Code Spaces dev
- remove Dockerfile-Dev
- don't target cloud shell

- Host developer experience review for each language - local and code spaces

**Comment by jofultz** [comment]
@jyotsnaravikumar, there are some missing extensions in the devcontainer.json file for Java.  As you're working on this it would be good to update the devontainer.json to include the extensions below:
- davidanson.vscode-markdownlint-0.36.0
- eamodio.gitlens-10.2.1
- gabrielbb.vscode-lombok-1.0.1
- redhat.java-0.62.0
- redhat.vscode-xml-0.11.0
- sonarsource.sonarlint-vscode-1.15.0
- visualstudioexptteam.vscodeintellicode-1.2.7
- vscjava.vscode-java-debug-0.26.0
- vscjava.vscode-java-dependency-0.10.2
- vscjava.vscode-java-pack-0.9.1
- vscjava.vscode-java-test-0.22.4
- vscjava.vscode-maven-0.21.4

**Comment by jyotsnaravikumar** [comment]
Implemented this task as part of https://github.com/retaildevcrews/helium-java/issues/255 in PR - https://github.com/retaildevcrews/helium-java/pull/259

**Comment by jyotsnaravikumar** [comment]
My observation on testing Helium-Java Codespaces

- When I run F5 on a fresh Codespace

  - launch.json does not get invoked from docs/vscode-template folder. It always looks for them in .vscode folder.
  - The same behavior with tasks.json as well
  - Hence to test we would've have to copy the launch.json from docs/vscode-template to .vscode
  - Not sure if this is maven specific codespace behavior.
  - The "args" did not work for helium java . Hence I used the "env" variable.
  - https://stackoverflow.com/questions/59687712/how-to-set-java-environment-variable-in-vs-code
  - ERROR com.cse.helium.app.services.configuration.ConfigurationService.<init> (45) - Max retries 3 times exceeded. Error Details: Tried AzureCliCredential but failed to acquire a token for any of them. Please verify the environment for either of them and see more details in the causes below.
  - Seems like it still does not pick environment variable.

- When I run mvn clean package from bash
   - mvn clean package
   - export KEYVAULT_NAME={my_keyvault_name}
   - az login
   - Everything works smooth
	
- Now Run F5 again
   - Now it picks environment variable here
   - Everything works smooth
