### ISSUE TITLE
M8 Goals

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#399]
- Java 1.0
- MIKV * 3
- IETF * 3
- Sharing/Documentation * 10

**Comment by wereinse** [comment]
Theme #1 
Sharing (SDKs, bugs, CSE and other bug feedback, Webcasts, Codespaces, use of Retrospected for Helium and organization - learned to use w/o link from ADO). Culture of integrating sharing as an accelerator and can serve to replace in person interaction.

Theme #2 
Reusability (MIKV x3, IETF x3)

Lesson Learned (should have done some webcasts a while back, even if we had to do an update, use of Retrospected)
