### ISSUE TITLE
[DoDREVIEW] iac DoD review

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#442]
This checklist is for verifying all User Story Acceptance Criteria and Definition of Done (DoD) have been completed in order to move User Story to "Done".

## IaC User Story

As a DevOps engineer, I want a repeatable way to deploy infrastructure as code via CI-CD that is secure by default and follows engineering best practices.
References #343 

## Acceptance Criteria
- [x] Provide a step-by-step quick start that delivers a positive developer experience
- [x] Securely build, deploy and alert on key infrastructure components (development, testing, staging, and production)
- [x] Securely build, deploy and adhere to guidelines and engineering best practices
- [x] Securely store secrets in Key Vault for Cosmos DB creation
- [X] Create the webhook for ACR (Azure Container Registry) 
- [x] Securely create a Cosmos DB with a customer defined Request Units (RUs)
- [x] Create AppInsights 
- [x] Automatically generate documentation (README's) from markdown text in each TF module
- [x] Use Terraform tfvars file for sensitive and secret information needed to build infrastructure to avoid secrets from being stored in Github
- [x] Use TF module format for each infrastructure area so future developers can easily maintain
- [x] Use sample TF module creation that is complex enough to support Helium and future expansion
- [x] Store tfstate file securely in Azure Blobs
- [x] Provide the capability to customize, create and deploy the resources below to support Helium (per language):
    * Easily customizable via tfvars files
    * DevOps via GitHub actions
    * CI-CD validation via GitHub actions
    * Azure Container Registry (ACR) 
    * Azure Container Instance (ACI) with docker image pushed for each endpoint
    * Azure App Service
    * CosmosDB secured via KeyVault
    * AKS Endpoints: bluebell, gelato, sherbert .cloudapp.centralus.azure.net
    * Application insights to monitor each AppService endpoint
    * Azure health checks on AppService endpoints
    * Monitoring / Observability with logging and alerting

## Definition of Done
- [x] Code Review completed
- [x] All existing automated code rolls out and is validated
- [x] Code changes checked into master
- [x] Sync github actions from master template
- [x] Existing documentation is updated (readme, .md's)
- [x] New documentation needed to support the change is created
- [x] CI completes successfully
- [x] CD completes successfully

Engineering Playbook [Definition of Done](https://github.com/microsoft/code-with-engineering-playbook/blob/master/team-agreements/definition-of-done/readme.md)

## Next Steps
- [x] Release template created

**Comment by wereinse** [comment]
Just committing so can work on in vscode

**Comment by wereinse** [comment]
Just committing again to save changes.
