### ISSUE TITLE
CSE Feedback on ACI

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#448]
Currently, ACI forces you to add the entrypoint to the command that it executes
  - this caused us over a week of downtime
  - you should be able to just specify the parameters like you can with docker run

**Comment by aflinchb** [comment]
Siva, Akinlolu and I just went through and submitted the CSE feedback together: https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/371702/
