### ISSUE TITLE
Update code / docs for new Cosmos DB features

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#449]
Need to look at
- data model (can we drop textSearch?)
- composite indexes
- queries
- benchmark performance
- potentially load a larger data set (it was too slow to use before)

https://devblogs.microsoft.com/cosmosdb/new-string-function-performance-improvements-and-case-insensitive-search/

**Comment by dsturgell** [comment]
Need to change:
 - Benchmark performance (performance gains & cost savings)
- Queries
