### ISSUE TITLE
Update/fix Demo-in-a-box (AKS) readme

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium#459]
## Description
- The readme for AKS needs to be updated with latest improvements to developer documentation (i.e. not saving secrets directly to environment variables
- Currently, I was unable to successfully complete the walkthrough.

## Expected Behavior
- Infrastructure steps are aligned with main helium readme (this is mostly complete, but would be worth revisiting)
- You can successfully query the heilum endpoints on the instance running on aks. 

## Reproduce
1. Go through the current walkthrough steps.  
2. Notice that the following step fails
# curl the health check endpoint
curl ${INGRESS_PIP}.nip.io/healthz
3.  Check the logs of the linkerd-proxy container and see the following errors:
ERR! [     4.404521s] linkerd2_proxy::app::errors unexpected error: error trying to connect: Connection refused (os error 111) (address: 127.0.0.1:4120)
ERR! [    14.403892s] linkerd2_proxy::app::errors unexpected error: error trying to connect: Connection refused (os error 111) (address: 127.0.0.1:4120)
ERR! [    24.403881s] linkerd2_proxy::app::errors unexpected error: error trying to connect: Connection refused (os error 111) (address: 127.0.0.1:4120)
ERR! [    34.403788s] linkerd2_proxy::app::errors unexpected error: error trying to connect: Connection refused (os error 111) (address: 127.0.0.1:4120)

- I tried reverting back to older versions of helm, linkerd, and K8s, but still hit the same issue

**Comment by AAkindele** [comment]
fixed with https://github.com/retaildevcrews/helium/pull/545
