### ISSUE TITLE
Create debug version of webv container

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#467]
- Create debug version of webv container with full bash shell and IP utilities
- This will allow us to debug latency issues with tracert, etc.
- tag with :debug
- update ci-cd to build at the same time as :beta

**Comment by sivamu** [comment]
Packages installed in debug image:
```
(1/13) Installing nghttp2-libs (1.41.0-r0)
(2/13) Installing libcurl (7.69.1-r0)
(3/13) Installing curl (7.69.1-r0)
(4/13) Installing libcap (2.27-r0)
(5/13) Installing iputils (20190709-r0)
(6/13) Installing mii-tool (1.60_git20140218-r2)
(7/13) Installing net-tools (1.60_git20140218-r2)
(8/13) Installing lua5.3-libs (5.3.5-r6)
(9/13) Installing libpcap (1.9.1-r2)
(10/13) Installing pcre (8.44-r0)
(11/13) Installing libssh2 (1.9.0-r1)
(12/13) Installing nmap (7.80-r2)
(13/13) Installing tcpdump (4.9.3-r1)
```

[Contents of iputils](https://pkgs.alpinelinux.org/contents?branch=edge&name=iputils&arch=ppc64le&repo=main)
[Contents of nettools](https://pkgs.alpinelinux.org/contents?branch=edge&name=net-tools&arch=mips64&repo=main)
