### ISSUE TITLE
Variance in Response Time

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#480]
- I noticed a perf issue when I deployed bluebell with TF
- I had changed TF to use 64 bit and the average response was in the 30s
- After changing to 32 bit, it's down to 13ms which is pretty normal at 75 req/min
- We should do a more thorough test across all of the languages
- I wouldn't expect a difference and certainly not over 2X

Next Steps:
- [x] Document
- [ ]  Test with VNET
- [ ] Partner with SA (Native Apps & Experiences)

**Comment by dsturgell** [comment]
I think this is an opportunity to partner with the SA and file CSE feedback.
