### ISSUE TITLE
Change references of old service name MSI to MI (Managed Identity)

### ISSUE THREAD

**Issue by sivamu** [retaildevcrews/helium#501]
## Description
Upon reviewing the Azure docs, Managed Identity 'is the new name for the service formerly known as Managed Service Identity (MSI)'. There are references in code (specifically the Key Vault client Initialization for each helium service) and documentation for this old term that will need to be modified to avoid confusion.

**Comment by swapniljha001** [comment]
I've changed all the references of MSI to MI, and have submitted Pull Requests for the same. I'm new to this so my contributing message might not be 100%  accurate to the guidelines. Sorry about that. @sivamu

**Comment by sivamu** [comment]
No worries, thanks for submitting the changes! @swapniljha001
