### ISSUE TITLE
API testing - update webv readme

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#530]
Add a link / short writeup to webv readme based on the story Eddie shared in chat. Good chance to document how we run 7x24 with observability so that we know when something changes

Another example of why we were so detailed on our api test and the exact reason why web validate exists!!
https://devops.com/how-api-testing-can-save-you-thousands/

**Comment by bartr** [comment]
@alfredoihernandez - can you PR this into /microsoft/webvalidate early this week so that we can complete the 1.3.1 release?

**Comment by alfredoihernandez** [comment]
> webvalidate early this week so that we can complete the 1.3.1 release?

Sure, I don't see microsoft/webvalidate repo so I've placed draft changes in retaildevcrews/webvalidate
