### ISSUE TITLE
Some Helium smoker ACI containers are not showing up to date logs

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/helium#620]
## Description

- `gelato-webv-westus2` and `sherbert-webv-westeurope` ACI containers are showing logs from October, 2020. The rest of the containers instances are showing up to date log messages.

## Expected Behavior

- Container instances show up to date logs.

## Reproduce

View the logs.

```
az login
az account set -s <subscription id or name>
az container logs -n sherbert-webv-westeurope -g helium-e2e-smoker-rg
```

## Additional Context

For example, as of 2020-11-11, here is the most recent log entry for sherbert-webv-westeurope.
```
{"date":"2020-10-28T17:50:16.6142013Z","server":"https://sherbert.azurewebsites.net","statusCode":200,"failed":false,"validated":true,"errorCount":0,"duration":1005,"contentLength":17420,"category":"SearchMovies","quartile":4,"tag":"westeurope","path":"/api/movies?year=1990","errors":[]}
```

**Comment by AAkindele** [comment]
Took a look again and one of the instances was back up. I restarted the other and logs are showing up again.

**Comment by jofultz** [comment]
Has it repeated or should we close this down for now?
