### ISSUE TITLE
Create Feature Template

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#73]

**Comment by dsturgell** [comment]
For quick review from team, this is what I am proposing for the Feature Request template.
@bartr @aflinchb @atxryan

- Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] 

- Describe the solution you'd like A clear and concise description of what you want to happen.  

- Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

- Describe why are we doing this? What use cases does it support?  Please focus on explaining the motivation so that if this proposal is not accepted, the motivation could be used to develop alternative solutions. In other words, enumerate the constraints you are trying to solve without coupling them too closely to the solution you have in mind. -->

- Additional context Add any other context or screenshots about the feature request here.

**Comment by aflinchb** [comment]
Looks great!

Only comment would be to remove the "Ex. I'm always frustrated when [...]"
