### ISSUE TITLE
Can we create a Cosmos SP for featured movie?

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#97]
Implementing /api/featured/movie is challenging because of some of the limitations in Spring Boot

Can we create a stored procedure in Cosmos that does the weighting and randomization and returns a single, random movie?

**Comment by jyotsnaravikumar** [comment]
@bartr : we may not need this, got it working with 2 simple calls exactly the same as C#

**Comment by bartr** [comment]
Since SPs don't support cross-partition operations, this won't work for us.

closing
